spring:
  application:
    name: ExcelToChart

  datasource:
    url: jdbc:postgresql://localhost:5432/etcdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
